$(document).ready(function(){

    $("#move").click(function(){
      multipolygon.deactivate();
      move.activate();
      $(".selected").removeClass("selected");
      $("#move").addClass("selected");
    });
    $("#pencil").click(function(){
      project.deselectAll();
      multipolygon.deactivate();
      pencil.activate();
      $(".selected").removeClass("selected");
      $("#pencil").addClass("selected");
    });
    $("#brush").click(function(){
      project.deselectAll();
      multipolygon.deactivate();
      brush.activate();
      $(".selected").removeClass("selected");
      $("#brush").addClass("selected");
    });
    $("#line").click(function(){
      project.deselectAll();
      multipolygon.deactivate();
      line.activate();
      $(".selected").removeClass("selected");
      $("#line").addClass("selected");
    });
    $("#rectangle").click(function(){
      project.deselectAll();
      multipolygon.deactivate();
      rectangle.activate();
      $(".selected").removeClass("selected");
      $("#rectangle").addClass("selected");
    });
    $("#ellipse").click(function(){
      project.deselectAll();
      multipolygon.deactivate();
      ellipse.activate();
      $(".selected").removeClass("selected");
      $("#ellipse").addClass("selected");
    });
    $("#multipolygon").click(function(){
      project.deselectAll();
      multipolygon.deactivate();
      multipolygon.activate();
      $(".selected").removeClass("selected");
      $("#multipolygon").addClass("selected");
    });
    $("#eraser").click(function(){
      project.deselectAll();
      multipolygon.deactivate();
      eraser.activate();
      $(".selected").removeClass("selected");
      $("#eraser").addClass("selected");
    });
    $("#delete").click(function(){
      multipolygon.deactivate();
      del();
      $(".selected").removeClass("selected");
      $("#move").addClass("selected");
    });
    $("#text").click(function(){
      multipolygon.deactivate();
      project.deselectAll();
      text.activate();
      $(".selected").removeClass("selected");
      $("#text").addClass("selected");
    });




    create_new_file();

});
